apiVersion: v1
kind: Pod
metadata:
  name: file-secret-pod
spec:
  containers:
    - name: app
      image: nginx
      volumeMounts:
        - name: secret-vol
          mountPath: /etc/secrets
          readOnly: true
  volumes:
    - name: secret-vol
      secret:
        secretName: db-secret
        items:
          - key: username
            path: db-user

#Result
#
#  /etc/secrets/db-user
