version: '3.8'

services:
    system-feature:
        build:
          context: .
          dockerfile: services/system/Dockerfile
        container_name: system
        ports:
          - "8001:8001"
    
    zookeeper:
      image: confluentinc/cp-zookeeper:7.6.0
      environment:
        ZOOKEEPER_CLIENT_PORT: 2181
        ZOOKEEPER_TICK_TIME: 2000
    
    kafka:
      image: confluentinc/cp-kafka:7.6.0
      depends_on: [zookeeper]
      ports: ["9092:9092"]
      environment:
        KAFKA_BROKER_ID: 1
        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
        KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    
    producer:
      build:
        context: .
        dockerfile: kafka-example/producer/Dockerfile.producer
      depends_on: [kafka]
      environment:
        KAFKA_BROKERS: kafka:9092

    consumer:
      build:
        context: .
        dockerfile: kafka-example/consumer/Dockerfile.consumer
      depends_on: [kafka]
      environment:
        KAFKA_BROKERS: kafka:9092

    ubuntu-server:
      build:
        context: .
        dockerfile: Dockerfile.ubuntu
      container_name: ubuntu-server
      ports:
        - "8002:8002"
