services:
  dynamodb:
    image: amazon/dynamodb-local:latest
    ports:
      - "8000:8000"
    command: -jar DynamoDBLocal.jar -sharedDb -inMemory

  go-app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DYNAMODB_TABLE=local-table
      - DYNAMODB_ENDPOINT=http://dynamodb:8000
    depends_on:
      - dynamodb

  dynamodb-cli:
    image: amazon/aws-cli
    entrypoint: sh  # âœ… OVERRIDES aws ENTRYPOINT
    command: -c "sleep 3600"
    environment:
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=dummy
      - AWS_SECRET_ACCESS_KEY=dummy
    depends_on: [dynamodb]
    networks: [default]
