apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: system-ingress
spec:
  rules:
    - host: system.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: system-service
                port:
                  number: 8001